import AppFooter from "@/components/Footer/app.footer";
import AppHeader from "@/components/Header/app.header";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <AppHeader />
      {children}
      <div style={{ marginTop: "100px" }}></div>
      <AppFooter />
    </>
  );
}
